#Engagement API ------------------------
engagement_settings:
  name: test   #Session name for data set, used to label output.
  endpoint: historical    #options: totals, 28hr, historical.
  inbox: ./inbox #Tweet inbox (HPT gz files? Search JSON?, CSV database dump?)
  outbox: ./outbox     #Engagement API output is written here.
  name_based_folders: true
  max_top_tweets: 10                 #Set to zero to turn 'top Tweet' processing off.
  start: 201603021200                   #historical endpoint, defaults to now - 28 days.
  #end: 2015-12-10                     #historical endpoint, defaults to now.
  save_ids: false                      #TODO: Not implemented yet.
  save_api_responses: true            #Saves Engagement API responses to a 'api_responses' subfolder of the 'outbox'.
  verbose: true                       #More status fyi written to system out while running.
  rate_limit_requests: 60           #Set these to help avoid request rate limits.
  rate_limit_seconds: 60              #Time between calls equals rate_limit_seconds/rate_limit_requests (60/4 = 15) seconds.

engagement_types: #iorder here is echoed in output.
  impressions: true
  engagements: true
  favorites: true
  retweets: true
  replies: true
  url_clicks: false
  hashtag_clicks: false
  detail_expands: false
  media_clicks: false
  permalink_clicks: false
  app_opens: false
  app_install_attempts: false
  email_tweet: false
  
engagement_groupings:
  by_type:  #Grand totals.
    - engagement.type
  by_tweet_type: #Needed for surfacing Top Tweets. I.e., the 'top Tweet' code depends on this specific API output.
    - tweet.id
    - engagement.type
# hourly_timeseries:
#   - engagement.type
#   - tweet.id
#   - engagement.hour
#  by_tweet:
#  - tweet.id
#  by_tweet_type:
#  - tweet.id
#  - engagement.type
#  by_day_type:
#  - engagement.day
#  - engagement.type
#  by_type_day_tweet:
#  - engagement.type
#  - engagement.day
#  - tweet.id

logging:
  name: engagement_app.log
  log_path: ./log
  warn_level: debug
  size: 1 #MB
  keep: 2
